services:
  frontend:
    container_name: frontend
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/traveltracker"
      JWT_SECRET_KEY: "super-secret-key"
      EXCHANGE_RATE_API_KEY: "your-api-key"
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo
    container_name: traveltracker-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongo-data:/data/db

volumes:
  mongo-data:
