version: "3.9"
services:
  mongo:
    image: mongo
    container_name: traveltracker-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: traveltracker-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/traveltracker
      - JWT_SECRET_KEY=your-super-secret-key
      - EXCHANGE_RATE_API_KEY=your-exchange-rate-api-key
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    container_name: traveltracker-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:

